services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/octane
      - PORT=3000
      - ENV=dev
      - JWT_SECRET=octane
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    command: ['npm', 'run', 'start']

  postgres:
    image: postgres:17.2
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=octane
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
